### ISSUE TITLE
Redundant -ansi option in gcc.mk

### ISSUE THREAD

**Issue by jwakely** [gennaroprota/breath#1]
`build/gcc.mk` has:

````
cpp_basic_options =  -ansi                      \
                     -std=c++14                 \
````

This is silly because `-ansi` is exactly equivalent to `-std=c++98` and so obviously serves no purpose if you immediately follow it by a different `-std` option.

**Comment by jwakely** [comment]
P.S. yes, I've seen the comment in the file. It's wrong. Although it's true that `-ansi` prevents macros like `unix` being defined, so do all the `-std=c++NN` options (including `-std=c++14`).

**Comment by gennaroprota** [comment]
On Tue, Oct 2, 2018 at 1:39 PM Jonathan Wakely <notifications@github.com>
wrote:

> P.S. yes, I've seen the comment in the file. It's wrong. Although it's
> true that -ansi prevents macros like unix being defined, so do all the
> -std=c++NN options (including -std=c++14).
>
As the comment in the file says, I encountered the issue with gcc 4.7.3 under
Cygwin and gcc 4.7.1 under Slackware 14.0 x86_64. I no longer have those
versions to verify. I think you do have both, though perhaps not under
Cygwin and Slackware. Could you please run

    g++ -std=c++11 -E -dM - < /dev/null

?

-- 
--
.:: Gennaro Prota ::.
.:: https://about.me/gennaro.prota <http://about.me/gennaro.prota> ::.

**Comment by gennaroprota** [comment]
On Tue, Oct 2, 2018 at 2:28 PM Gennaro Prota <gennaro.prota@gmail.com>
wrote:

> Could you please run
>
>     g++ -std=c++11 -E -dM - < /dev/null
>
> ?
>

Actually, if I run the above, I get (with gcc 7.3.0 under Cygwin):

  cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++
but not for C

so probably it doesn't take the -std= option. But you might try compiling
something like:

  #ifdef unix
  #    error ouch!
  #endif

-- 
--
.:: Gennaro Prota ::.
.:: https://about.me/gennaro.prota <http://about.me/gennaro.prota> ::.

**Comment by jwakely** [comment]
You need to specify the language of the input when preprocessing from standard input, i.e. `g++ -std=c++11 -E -dM -x c++ -`

[The manual](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html) is clear, `-ansi` is exactly equivalent to `-std=c++98`, and so is completely redundant when followed by a different `-std` option.

`unix` is not defined when compiling with **any** `-std=c++NN` option, this is [documented in the cpp manual](https://gcc.gnu.org/onlinedocs/cpp/System-specific-Predefined-Macros.html)

Compiling with `-std=c++11` does not defined `unix`:
````
$ ~/gcc/7/bin/g++ -std=c++11 -E -dM -x c++ - < /dev/null | egrep 'unix|STRICT'
#define __unix__ 1
#define __unix 1
#define __STRICT_ANSI__ 1
````
Adding `-ansi` first makes no difference:
````
$ ~/gcc/7/bin/g++ -ansi -std=c++11 -E -dM -x c++ - < /dev/null | egrep 'unix|STRICT'
#define __unix__ 1
#define __unix 1
#define __STRICT_ANSI__ 1
````
Compiling with `-std=gnu++11` _does_ define `unix` **even when it follows `-ansi`**:
````
$ ~/gcc/7/bin/g++ -ansi -std=gnu++11 -E -dM -x c++ - < /dev/null | egrep 'unix|STRICT'
#define __unix__ 1
#define __unix 1
#define unix 1
````
And that's because the `-ansi` option is completely redundant when followed by any other `-std` option.

If you want to prevent `unix` and similar macros being defined without reserved names, just use ` -std=c++NN` option, don't use `-ansi` first because it does **nothing**.

**Comment by gennaroprota** [comment]
On Tue, Oct 2, 2018 at 3:26 PM Jonathan Wakely <notifications@github.com>
wrote:

> See "The results are identical when using 4.7.1 and 4.7.3 instead:" in my
> last comment (edited after the initial comment).
>
Oops, I hadn't seen the edit. So... I might guess that this was a Cygwin
issue, but I also mention Slackware so... I likely messed up :-/ Thank you
so much for your patience, I'll fix the issue as soon as possible.
